apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: portainer-transport
  namespace: portainer
spec:
  serverName: portainer
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: portainer
  name: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.localhost`)
      kind: Rule
      services:
        - name: portainer
          kind: Service
          port: 9443
          serversTransport: portainer-transport