apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/host/c/Docker-Storage/js
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - example-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-pod
# spec:
#   containers:
#     - name: my-container
#       image: nginx
#       resources:
#         limits:
#           memory: 512Mi
#           cpu: "1"
#         requests:
#           memory: 256Mi
#           cpu: "0.2"
#       volumeMounts:
#         - name: my-pvc
#           mountPath: /usr/share/nginx/html
#           accessMode: ReadWriteOnce
#   volumes:
#     - name: my-pvc
#       persistentVolumeClaim:
#         claimName: my-pvc