apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-nodejs # Name of the deployment
  namespace: sampleapp # Name of the namespace
  labels:
    app: sampleapp-nodejs # Name of your application
spec:
  selector:
    matchLabels:
      app: sampleapp-nodejs # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: sampleapp-nodejs # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: sampleapp-nodejs # Name of the container
        image: localhost:5000/sampleapp-nodejs # The image you want to run
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # The port that your application uses
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name:  sampleapp-nodejs
  namespace: sampleapp
spec:
  selector:
    app:  sampleapp-nodejs
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: sampleapp
  name: sampleapp-nodejs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nodejs.localhost`)
      kind: Rule
      services:
        - name: sampleapp-nodejs
          kind: Service
          port: 8080