---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: sampleapp
  name: whoami
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.localhost`) && (PathPrefix(`/path1`) || PathPrefix(`/path2`))
      kind: Rule
      services:
        - name: whoami
          kind: Service
          port: 80